from .asignatura import *
from .carrera import *
from .disciplina import *
from .evento import *
from .indicador_evaluacion import *
from .premio import *
from .profesor import *
from .publicacion import *
from .profesor_evento import *
from .profesor_asignatura import *
from .profesor_premio import *
from .profesor_publicacion import *
from .profesor_evaluacion import *
