# Generated by Django 5.1.5 on 2025-05-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=255)),
                ("modalidad", models.CharField(db_column="modalidad", max_length=255)),
                ("sede", models.CharField(db_column="sede", max_length=255)),
                (
                    "anno_eval_ext",
                    models.CharField(db_column="anno_eval_ext", max_length=255),
                ),
                (
                    "curso_evaluado",
                    models.CharField(db_column="curso_evaluado", max_length=255),
                ),
                ("numero_eval_ext", models.IntegerField(db_column="numero_eval_ext")),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
                "db_table": "sgac_carreras",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.IntegerField(db_column="anno")),
                ("titulo", models.CharField(db_column="titulo", max_length=500)),
                (
                    "titulo_corto",
                    models.CharField(db_column="titulo_corto", max_length=255),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("INTERNACIONAL", "Internacional"),
                            ("NACIONAL", "Nacional"),
                            ("PROVINCIAL", "Provincial"),
                            ("MUNICIPAL", "Municipal"),
                            ("DE_BASE", "De base"),
                        ],
                        db_column="clasificacion",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "sgac_eventos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IndicadorEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=255)),
            ],
            options={
                "verbose_name": "Indicador de Evaluacion",
                "verbose_name_plural": "Indicadores de Evaluacion",
                "db_table": "sgac_indicadoresevaluacion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Premio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=100)),
            ],
            options={
                "verbose_name": "Premio",
                "verbose_name_plural": "Premios",
                "db_table": "sgac_premios",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=255)),
                (
                    "primer_apellido",
                    models.CharField(db_column="primer_apellido", max_length=255),
                ),
                (
                    "segundo_apellido",
                    models.CharField(db_column="segundo_apellido", max_length=255),
                ),
                (
                    "annos_experiencia_carrera",
                    models.IntegerField(
                        db_column="annos_experiencia_carrera", default=0
                    ),
                ),
                (
                    "annos_experiencia_mes",
                    models.IntegerField(db_column="annos_experiencia_mes", default=0),
                ),
                (
                    "categoria_docente",
                    models.CharField(
                        choices=[
                            ("INSTRUCTOR", "Instructor"),
                            ("ASISTENTE", "Asistente"),
                            ("AUXILIAR", "Auxiliar"),
                            ("TITULAR", "Titular"),
                            ("ATD", "ATD"),
                        ],
                        db_column="categoria_docente",
                        max_length=255,
                    ),
                ),
                (
                    "grado_cientifico",
                    models.CharField(
                        choices=[
                            ("DOCTOR_EN_CIENCIA", "Doctor En Ciencia"),
                            ("DOCTOR_EN_CIENCIAS", "Doctor En Ciencias"),
                        ],
                        db_column="grado_cientifico",
                        max_length=255,
                    ),
                ),
                ("correos", models.JSONField(db_column="correos", default=dict)),
                ("telefonos", models.JSONField(db_column="telefonos", default=dict)),
            ],
            options={
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
                "db_table": "sgac_profesores",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Publicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.IntegerField(db_column="anno")),
                ("titulo", models.CharField(db_column="titulo", max_length=500)),
                (
                    "revista_editorial",
                    models.CharField(db_column="revista_editorial", max_length=500),
                ),
                (
                    "tipo_publicacion",
                    models.CharField(db_column="tipo_publicacion", max_length=500),
                ),
                ("isbn_issn", models.CharField(db_column="isbn_issn", max_length=500)),
                (
                    "verificacion_libro",
                    models.CharField(db_column="verificacion_libro"),
                ),
                (
                    "base_datos_revista",
                    models.CharField(db_column="base_datos_revista", max_length=500),
                ),
                (
                    "verificacion_referencia",
                    models.CharField(db_column="verificacion_referencia"),
                ),
                ("nivel", models.IntegerField(db_column="nivel")),
            ],
            options={
                "verbose_name": "Publicacion",
                "verbose_name_plural": "Publicaciones",
                "db_table": "sgac_publicaciones",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PublicacionClasificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=255)),
            ],
            options={
                "verbose_name": "Clasificacion Publicacion",
                "verbose_name_plural": "Clasificaciones Publicacion",
                "db_table": "sgac_clasificacionespublicacion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_column="codigo", max_length=255)),
                ("nombre", models.CharField(db_column="nombre", max_length=255)),
                (
                    "carrera",
                    models.ForeignKey(
                        db_column="id_carrera",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinas",
                        to="sgac.carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "db_table": "sgac_disciplinas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=255)),
                ("codigo", models.CharField(db_column="codigo", max_length=100)),
                (
                    "anno",
                    models.IntegerField(
                        choices=[
                            (1, "Primer Año"),
                            (2, "Segundo Año"),
                            (3, "Tercer Año"),
                            (4, "Cuarto Año"),
                            (5, "Quinto Año"),
                            (6, "Sexto Año"),
                        ],
                        db_column="anno",
                    ),
                ),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "Primer Semestre"), (2, "Segundo Semestre")],
                        db_column="semestre",
                    ),
                ),
                ("modalidad", models.CharField(db_column="modalidad", max_length=255)),
                (
                    "curriculo",
                    models.CharField(
                        choices=[
                            ("BASE", "Base"),
                            ("PROPIO", "Propio"),
                            ("OPTATIVA", "Optativa"),
                            ("ELECTIVA", "Electiva"),
                        ],
                        db_column="curriculo",
                        max_length=255,
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        db_column="id_disciplina",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaturas",
                        to="sgac.disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
                "db_table": "sgac_asignaturas",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfesorAsignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        db_column="id_asignatura",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.asignatura",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        db_column="id_profesor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor Asignatura",
                "verbose_name_plural": "Profesor Asignaturas",
                "db_table": "sgac_profesores_asignaturas",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="profesor",
            name="asignaturas",
            field=models.ManyToManyField(
                through="sgac.ProfesorAsignatura", to="sgac.asignatura"
            ),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="profesores",
            field=models.ManyToManyField(
                through="sgac.ProfesorAsignatura", to="sgac.profesor"
            ),
        ),
        migrations.CreateModel(
            name="ProfesorEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        db_column="id_evento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.evento",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        db_column="id_profesor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor Evento",
                "verbose_name_plural": "Profesor Eventos",
                "db_table": "sgac_profesores_eventos",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="profesor",
            name="eventos",
            field=models.ManyToManyField(
                through="sgac.ProfesorEvento", to="sgac.evento"
            ),
        ),
        migrations.CreateModel(
            name="ProfesorPremio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "premio",
                    models.ForeignKey(
                        db_column="id_premio",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.premio",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        db_column="id_profesor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor Premio",
                "verbose_name_plural": "Profesores Premios",
                "db_table": "sgac_profesores_premios",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfesorPublicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participacion",
                    models.CharField(
                        choices=[
                            ("AUTOR_PRINCIPAL", "Autor principal"),
                            ("COAUTOR", "Coautor"),
                        ],
                        db_column="participacion",
                        max_length=255,
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        db_column="id_profesor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.profesor",
                    ),
                ),
                (
                    "publicacion",
                    models.ForeignKey(
                        db_column="id_publicacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.publicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor Publicacion",
                "verbose_name_plural": "Profesores Publicaciones",
                "db_table": "sgac_profesores_publicaciones",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="publicacion",
            name="clasificacion",
            field=models.ForeignKey(
                db_column="id_clasificacion",
                on_delete=django.db.models.deletion.CASCADE,
                to="sgac.publicacionclasificacion",
            ),
        ),
    ]
