# Generated by Django 5.1.5 on 2025-05-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgac", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfesorEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluacion",
                    models.CharField(
                        choices=[
                            ("EXCELENTE", "Excelente"),
                            ("BIEN", "Bien"),
                            ("REGULAR", "Regular"),
                            ("MAL", "Mal"),
                        ],
                        db_column="evaluacion",
                    ),
                ),
                ("fecha", models.DateField(db_column="fecha")),
                (
                    "indicador",
                    models.ForeignKey(
                        db_column="id_indicador",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.indicadorevaluacion",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        db_column="id_profesor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sgac.profesor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor Evaluacion",
                "verbose_name_plural": "Profesores Evaluaciones",
                "db_table": "sgac_profesores_indicadorevaluacion",
                "managed": True,
            },
        ),
    ]
