# Generated by Django 5.1.5 on 2025-06-17 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgac", "0002_profesorevaluacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicacion",
            name="clasificacion",
        ),
        migrations.AlterField(
            model_name="profesor",
            name="categoria_docente",
            field=models.CharField(
                choices=[
                    ("INSTRUCTOR", "Instructor"),
                    ("ASISTENTE", "Asistente"),
                    ("AUXILIAR", "Auxiliar"),
                    ("TITULAR", "Titular"),
                    ("AD", "Adiestrado"),
                    ("ATD", "ATD"),
                ],
                db_column="categoria_docente",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="grado_cientifico",
            field=models.CharField(
                choices=[
                    ("DOCTOR", "Doctor"),
                    ("MASTER", "Máster"),
                    ("NINGUNO", "Ninguno"),
                ],
                db_column="grado_cientifico",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="publicacion",
            name="nivel",
            field=models.IntegerField(
                db_column="nivel",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="El nivel mínimo es 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        4, message="El nivel máximo es 4"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="publicacion",
            name="tipo_publicacion",
            field=models.CharField(
                choices=[
                    ("articulo", "Artículo"),
                    ("libro", "Libro"),
                    ("libro_digital", "Libro Digital"),
                    ("capitulo_libro", "Capítulo de Libro"),
                    ("texto_carrera", "Texto de la Carrera"),
                    ("material_docente", "Material Docente Interno"),
                    ("patente", "Patente"),
                ],
                db_column="tipo_publicacion",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="publicacion",
            name="verificacion_libro",
            field=models.CharField(db_column="verificacion_libro", max_length=500),
        ),
        migrations.AlterField(
            model_name="publicacion",
            name="verificacion_referencia",
            field=models.CharField(db_column="verificacion_referencia", max_length=500),
        ),
    ]
