# Generated by Django 5.1.5 on 2025-06-18 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgac", "0003_remove_publicacion_clasificacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="premio",
            name="nombre",
        ),
        migrations.AddField(
            model_name="premio",
            name="anno",
            field=models.IntegerField(db_column="anno", null=True),
        ),
        migrations.AddField(
            model_name="premio",
            name="clasificacion",
            field=models.CharField(
                choices=[
                    ("PREMIO_NACIONAL_ACC", "Premio nacional de la ACC"),
                    ("PREMIO_PROVINCIAL_ACC", "Premio provincial de la ACC"),
                    ("PREMIO_NACIONAL_CITMA", "Premio nacional del CITMA"),
                    ("PREMIO_PROVINCIAL_CITMA", "Premio provincial del CITMA"),
                    ("PREMIOS_EVENTOS_CIENTIFICOS", "Premios de eventos científicos"),
                    (
                        "PREMIOS_CIENTIFICOS_INTERNACIONALES",
                        "Premios científicos internacionales",
                    ),
                    ("DISTINCION_MINISTRO", "Distinción del ministro"),
                    ("PREMIO_RECTOR", "Premio del rector"),
                    ("PREMIO_DECANO", "Premio de decano"),
                    ("CONDECORACIONES_NACIONALES", "Condecoraciones nacionales"),
                    (
                        "CONDECORACIONES_INTERNACIONALES",
                        "Condecoraciones internacionales",
                    ),
                    (
                        "RECONOCIMIENTOS_ORG_ESTUDIANTILES",
                        "Reconocimientos de las organizaciones estudiantiles",
                    ),
                    ("OTROS_PREMIOS_CIENTIFICOS", "Otros premios científicos"),
                    ("OTROS", "Otros"),
                ],
                db_column="clasificacion",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="premio",
            name="descripcion",
            field=models.TextField(db_column="descripcion", null=True),
        ),
        migrations.AddField(
            model_name="premio",
            name="profesor",
            field=models.ForeignKey(
                db_column="id_profesor",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="premios",
                to="sgac.profesor",
            ),
        ),
    ]
