# Generated by Django 5.1.5 on 2025-06-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgac", "0005_alter_premio_anno_alter_premio_clasificacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="dr_especialidad_afin",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                db_column="dr_especialidad_afin",
                max_length=2,
                null=True,
            ),
        ),
    ]
