# Generated by Django 5.1.5 on 2025-06-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sgac", "0006_profesor_dr_especialidad_afin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicadorevaluacion",
            name="nombre",
            field=models.CharField(
                choices=[
                    (
                        "Trabajo docente-educativo en pregrado y posgrado",
                        "Trabajo docente-educativo en pregrado y posgrado",
                    ),
                    ("Trabajo político-ideológico", "Trabajo político-ideológico"),
                    ("Trabajo metodológico", "Trabajo metodológico"),
                    (
                        "Trabajo de investigación e innovación",
                        "Trabajo de investigación e innovación",
                    ),
                    ("Superación", "Superación"),
                    ("Extensión Universitaria", "Extensión Universitaria"),
                    (
                        "Funciones administrativas asignadas",
                        "Funciones administrativas asignadas",
                    ),
                    ("General", "General"),
                ],
                db_column="nombre",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="profesorevaluacion",
            name="evaluacion",
            field=models.CharField(
                choices=[
                    ("R", "Regular"),
                    ("B", "Bien"),
                    ("E", "Excelente"),
                    ("NP", "No Presentado"),
                ],
                db_column="evaluacion",
            ),
        ),
    ]
